### ISSUE TITLE
Lista zakupów

### ISSUE THREAD

**Issue by Noarkhh** [drobiu/drobiu#1]
- [x] Masło
- [x] Mydło 
- [x] Ręcznik papierowy 
- [x] chleb
- [x] rzeczy do tostów?
- [x] herbata Earl Grey !!! dilmah albo inna
- [x] dżem (mamy powidła)/ nutellą
- [x] winogrona
- [x] coś dobrego do picia
- [x] na grilla: ser halumi albo na grila, bataty, pieczarki, kurczak, kiełbasa, karkóweczka zamarynowana
- [x] keczup
- [x] czosnek
- [x] cebula
- [x] snaki: słone oraz słodkie (Kinder?)
- [x] pomidor
- [x] rzodkiewka 
- [x] jabłka 
- [x] rozpałka 
- [x] ser mozzarella w kulce (najlepiej light)
- [x] szpinak świeży 
- [x] klej kropelka
- [x] mąka 
- [x] piwo
- [x] jogurt grecki 400g
- [x] soda oczyszczona 
- [x] mozarella tarty 600g
- [x] 400g feta

**Comment by kruszyh** [comment]
- [x] kisiel
- [x] szpinak świeży +1

*Mydło w płynie do uzupełnienia dozownika

**Comment by kruszyh** [comment]
- [x] + 200g greckiego 
- [x] + 300g mozzarelli tartej
- [x]  + 200g fety 
- [x]  karton jajek

**Comment by kruszyh** [comment]
- [x] arbuz, jeśli się znajdzie więcej enjoyerów, niż Karol
*kisiele o smakach czerwonych

**Comment by drobiu** [comment]
Thanks for your contributions. Closing this issue until further notice. Feel free to reopen if new requirements appear :)

**Comment by integraledelebesgue** [comment]
There is not enough Rust here :(((
